server:
  port: 80
  servlet:
    context-path: /automation
#  ssl:
#    enable: true
#    key-store: /cert/keystore.p12
#    key-store-password: 123456
#    keyStoreType: PKCS12
#    keyAlias: tomcat
#    port: 8443
    
 
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

upload:
  filePath: 
    relativePath: /resources/
    PDFTemplatePath: C:\resources\

